/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2020-01-06 08:22:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class magazine_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head lang=\"ko\" id=\"hobbyful\">\r\n");
      out.write("<title>늘:솜씨</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"layout-wrap\">\r\n");
      out.write("\t\t\t<ul class=\"tab-class-list\">\r\n");
      out.write("\t\t\t\t<li class=\"tab-class\"><a href=\"#;\" data-mc-idx=\"all\" title=\"전체\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn-tab-class btn-tab-on\">전체</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"tab-class\"><a href=\"#;\" data-mc-idx=\"1\"\r\n");
      out.write("\t\t\t\t\ttitle=\"DIY RECIPE\" class=\"btn-tab-class\">DIY RECIPE</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"tab-class\"><a href=\"#;\" data-mc-idx=\"2\"\r\n");
      out.write("\t\t\t\t\ttitle=\"TREND\" class=\"btn-tab-class\">TREND</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"tab-class\"><a href=\"#;\" data-mc-idx=\"3\"\r\n");
      out.write("\t\t\t\t\ttitle=\"REVIEW\" class=\"btn-tab-class\">REVIEW</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"tab-class\"><a href=\"#;\" data-mc-idx=\"6\"\r\n");
      out.write("\t\t\t\t\ttitle=\"h-NEWS\" class=\"btn-tab-class\">h-NEWS</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"magazine-wrap\">\r\n");
      out.write("\t\t\t\t<ul class=\"class-list-wrap2\">\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=248\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"2019 하비풀 연말결산 이벤트\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/de1d19d0-2a54-11ea-9848-89ba67ca8f3c-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"2019 하비풀 연말결산 이벤트\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">하트어워드&amp;뿌듯챌린지 5배적립 이벤트!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">2019 하비풀 연말결산 이벤트</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.12.30 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=244\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"이번주, 적립금을 사용해도 줄지 않아요!\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/ecaa0860-2aa8-11ea-9848-89ba67ca8f3c-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"이번주, 적립금을 사용해도 줄지 않아요!\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코드 [마법의산타주머니]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">이번주, 적립금을 사용해도 줄지 않아요!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.12.23 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=243\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 올=\"\" 겨울=\"\" 최고의=\"\" 취미였어요\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/2bd9af20-2178-11ea-9cb3-c70fccd5674e-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 올=\"\" 겨울=\"\" 최고의=\"\" 취미였어요\"\"=\"\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">12월 3주차 뿌듯챌린지 100% 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"올 겨울 최고의 취미였어요\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.12.18 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=242\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"회원 환급 이벤트 \" 풀네임을=\"\" 외쳐주세요\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/15a31e40-2aaa-11ea-b5a7-4117d5d5495e-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"회원 환급 이벤트 \" 풀네임을=\"\" 외쳐주세요\"\"=\"\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">멤버십 등급에 따른 파격 환급 이벤트 (-50%)</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">회원 환급 이벤트 \"풀네임을 외쳐주세요\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.12.16 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=240\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 기억=\"\" 안나면=\"\" 영상을=\"\" 다시=\"\" 돌려봤어요\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/08362890-1c06-11ea-add4-09214dce28ac-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 기억=\"\" 안나면=\"\" 영상을=\"\" 다시=\"\" 돌려봤어요\"\"=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-class-list\" style=\"height: 100%;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">12월 2주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"기억 안나면 영상을 다시 돌려봤어요\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.12.11 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=239\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"그때그시절 동심찾기! 스킬자수 런칭 이벤트\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/9da2ee60-1a2e-11ea-add4-09214dce28ac-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"그때그시절 동심찾기! 스킬자수 런칭 이벤트\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코드 [빽투더초딩]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">그때그시절 동심찾기! 스킬자수 런칭 이벤트</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.12.09 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=238\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 어린=\"\" 시절에는=\"\" 학교에서=\"\" 많이=\"\" 했었는데...\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/2a91e930-167d-11ea-add4-09214dce28ac-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 어린=\"\" 시절에는=\"\" 학교에서=\"\" 많이=\"\" 했었는데...\"\"=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-class-list\" style=\"height: 100%;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">12월 1주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"어린 시절에는 학교에서 많이 했었는데...\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.12.04 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=233\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"재봉틀 클래스 런칭 행운 이벤트!\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/b72c0550-14d0-11ea-af2a-6372aa0ef6f4-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"재봉틀 클래스 런칭 행운 이벤트!\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코드 [행운의재봉틀]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">재봉틀 클래스 런칭 행운 이벤트!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.12.02 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=230\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 온라인클래스를=\"\" 비교해봐도=\"\" 답은=\"\" 하비풀!\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/03de7de0-1037-11ea-83c9-99a92107598f-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 온라인클래스를=\"\" 비교해봐도=\"\" 답은=\"\" 하비풀!\"\"=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-class-list\" style=\"height: 100%;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">11월 4주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"온라인클래스를 비교해봐도 답은 하비풀!\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.11.26 화요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=229\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"퇴근길타임특가&amp;대림미술관 초대 이벤트\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/32cdf1f0-1733-11ea-add4-09214dce28ac-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"퇴근길타임특가&amp;대림미술관 초대 이벤트\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코드 [워라밸타임특가]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">퇴근길타임특가&amp;대림미술관 초대 이벤트</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.11.25 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=228\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 신혼집을=\"\" 하비풀로=\"\" 꾸며봤어요\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/19748210-0b70-11ea-952c-efccbb50f547-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 신혼집을=\"\" 하비풀로=\"\" 꾸며봤어요\"\"=\"\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">11월 3주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"신혼집을 하비풀로 꾸며봤어요\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.11.20 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=224\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"하비풀 겨울 신규 가입자 이벤트\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/4009b390-1733-11ea-add4-09214dce28ac-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"하비풀 겨울 신규 가입자 이벤트\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">1년 무제한 수강권&amp;첫클래스 50% 할인혜택!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">하비풀 겨울 신규 가입자 이벤트</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.11.18 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=225\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"아크릴화 런칭 기념 그림반 할인 파티!\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/487ec560-1733-11ea-add4-09214dce28ac-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"아크릴화 런칭 기념 그림반 할인 파티!\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코드 [화가로망이루기]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">아크릴화 런칭 기념 그림반 할인 파티!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.11.18 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=223\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 무언가에=\"\" 도전하는게=\"\" 두렵지=\"\" 않을것=\"\" 같아요\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/65334030-0533-11ea-a7c7-8769acbff2c1-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 무언가에=\"\" 도전하는게=\"\" 두렵지=\"\" 않을것=\"\" 같아요\"\"=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-class-list\" style=\"height: 100%;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">11월 2주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"무언가에 도전하는게 두렵지 않을것 같아요\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.11.13 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=220\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"채색자수 오픈, 자수 10% 할인 파티!\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/aedc6220-01d2-11ea-a7c7-8769acbff2c1-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"채색자수 오픈, 자수 10% 할인 파티!\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">세상에는 이런 자수도 있어요!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">채색자수 오픈, 자수 10% 할인 파티!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.11.08 금요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=219\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 예쁜=\"\" 작품이=\"\" 나오니=\"\" 자존감도=\"\" 높아져요\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/517d7640-004d-11ea-a7c7-8769acbff2c1-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 예쁜=\"\" 작품이=\"\" 나오니=\"\" 자존감도=\"\" 높아져요\"\"=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-class-list\" style=\"height: 100%;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">11월 1주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"예쁜 작품이 나오니 자존감도 높아져요\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.11.06 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=218\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"커플로 하기 좋은 취미 추천&amp;환급 이벤트\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/bd66f5e0-fc77-11e9-bce7-bb5409fe61d5-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"커플로 하기 좋은 취미 추천&amp;환급 이벤트\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코드 [커플도 하비풀]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">커플로 하기 좋은 취미 추천&amp;환급 이벤트</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.11.04 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=217\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 솔직히=\"\" 택배=\"\" 받고=\"\" 넘=\"\" 당황스러웠어요\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/e93f7000-faee-11e9-bce7-bb5409fe61d5-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 솔직히=\"\" 택배=\"\" 받고=\"\" 넘=\"\" 당황스러웠어요\"\"=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-class-list\" style=\"height: 100%;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">10월 5주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"솔직히 택배 받고 넘 당황스러웠어요\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.30 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=216\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"나만의 취밋길을 찾아드립니다!\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/15296160-f718-11e9-9c82-5978e3ec6dff-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"나만의 취밋길을 찾아드립니다!\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코트 [나만의취밋길추천]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">나만의 취밋길을 찾아드립니다!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.25 금요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=214\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"(결과발표완료) 태교뜨개질 체험단 모집\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/d5cd03c0-f620-11e9-9c82-5978e3ec6dff-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"(결과발표완료) 태교뜨개질 체험단 모집\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">예비엄마라면 누구나!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">(결과발표완료) 태교뜨개질 체험단 모집</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.24 목요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=215\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 이번에는=\"\" 우리=\"\" 가족사진을=\"\" 그려봤어요\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/4f19e200-f600-11e9-9c82-5978e3ec6dff-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 이번에는=\"\" 우리=\"\" 가족사진을=\"\" 그려봤어요\"\"=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-class-list\" style=\"height: 100%;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">10월 4주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"이번에는 우리 가족사진을 그려봤어요\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.23 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=212\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"월화수목금 그림반 릴레이 할인!\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/e4d54fd0-f0c1-11e9-9062-1dadd702ba46-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"월화수목금 그림반 릴레이 할인!\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코드 [그림반릴레이할인]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">월화수목금 그림반 릴레이 할인!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.21 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=213\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"하비풀 오분취미살롱 @현대백화점 판교점\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/ba6c2f30-f0c0-11e9-9062-1dadd702ba46-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"하비풀 오분취미살롱 @현대백화점 판교점\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미살롱주인 하비풀</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">하비풀 오분취미살롱 @현대백화점 판교점</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.17 목요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=211\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 배우고=\"\" 혼자=\"\" 그려본=\"\" 나만의=\"\" 작품\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/d4a1ee90-effc-11e9-ac24-737b6e1628bf-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 배우고=\"\" 혼자=\"\" 그려본=\"\" 나만의=\"\" 작품\"\"=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-class-list\" style=\"height: 100%;\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">10월 3주차 뿌듯챌린지 환급자 발표</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"배우고 혼자 그려본 나만의 작품\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.16 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=210\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"새 친구 '오일파스텔'을 소개합니다!\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/5e848cd0-ee45-11e9-ac24-737b6e1628bf-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"새 친구 '오일파스텔'을 소개합니다!\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코드 [그림반 새친구]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">새 친구 '오일파스텔'을 소개합니다!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.14 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=209\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 함꼐하면=\"\" 즐거움이=\"\" 두=\"\" 배\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/594d3220-ee4b-11e9-ac24-737b6e1628bf-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 함꼐하면=\"\" 즐거움이=\"\" 두=\"\" 배\"\"=\"\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">10월 2주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"함꼐하면 즐거움이 두 배\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.09 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=208\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"폰드로잉 궁금한 사람 모여라!\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/0db5d140-e6d6-11e9-8946-f7c44655dc1e-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"폰드로잉 궁금한 사람 모여라!\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코드 [폰드로잉이알고싶다]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">폰드로잉 궁금한 사람 모여라!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.07 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=207\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 귀여운=\"\" 작가님=\"\" 목소리에=\"\" 힐링\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/ec597f20-e693-11e9-8946-f7c44655dc1e-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 귀여운=\"\" 작가님=\"\" 목소리에=\"\" 힐링\"\"=\"\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">10월 1주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"귀여운 작가님 목소리에 힐링\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.10.02 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=206\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"하비풀 DIY 스토어 오픈!\"><div class=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/ed765d80-e335-11e9-8f92-adaf2466574e-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"하비풀 DIY 스토어 오픈!\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">취미코드 [혼자서도잘해요]</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">하비풀 DIY 스토어 오픈!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.09.30 월요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=205\"\r\n");
      out.write("\t\t\t\t\t\ttitle=\"\" 재료비=\"\" 따로=\"\" 안드니까=\"\" 좋아요\"\"=\"\"><div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"class-list-thumb\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/e0466fe0-e00d-11e9-8fd9-7d4b59dd5b69-resize.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\talt=\"\" 재료비=\"\" 따로=\"\" 안드니까=\"\" 좋아요\"\"=\"\" class=\"thumb-class-list\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"height: 100%;\"><span class=\"thumb-slide-play\">재생</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"class-list-cont\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-tit\">9월 4주차 뿌듯챌린지 환급자 발표!</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-txt\">\"재료비 따로 안드니까 좋아요\"</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t2019.09.25 수요일 <span class=\"thumb-slide-link-nick\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=201\" title=\"안들으면 손해, 홈카페 클래스!\"><div class=\"class-list-thumb\"><img src=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/c18ebf00-dda9-11e9-b03b-e7350761990d-resize.jpg\" alt=\"안들으면 손해, 홈카페 클래스!\" class=\"thumb-class-list\" style=\"height:100%;\"><span class=\"thumb-slide-play\">재생</span></div><div class=\"class-list-cont\"><p class=\"class-list-tit\">취미코드 [홈카페일리있네]</p><p class=\"class-list-txt\">안들으면 손해, 홈카페 클래스!</p><p class=\"class-list-info\">2019.09.23 월요일 <span class=\"thumb-slide-link-nick\"></span></p></div></a></li>\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"class-list\"><a href=\"view-magazine.html?id=202\" title=\"\" 남편이=\"\" 밤새=\"\" 다=\"\" 했어요\"\"=\"\"><div class=\"class-list-thumb\"><img src=\"https://s3.ap-northeast-2.amazonaws.com/staticdev.hobbyful.co.kr/magazine/a6ab1a60-ddd3-11e9-b03b-e7350761990d-resize.jpg\" alt=\"\" 남편이=\"\" 밤새=\"\" 다=\"\" 했어요\"\"=\"\" class=\"thumb-class-list\" style=\"height:100%;\"><span class=\"thumb-slide-play\">재생</span></div><div class=\"class-list-cont\"><p class=\"class-list-tit\">9월 3주차 뿌듯챌린지 환급자 발표!</p><p class=\"class-list-txt\">\"남편이 밤새 다 했어요\"</p><p class=\"class-list-info\">2019.09.20 금요일 <span class=\"thumb-slide-link-nick\"></span></p></div></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"class-list-more-btn\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:;\" title=\"more\" class=\"btn-more\">more</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"fb-root\" class=\" fb_reset\"><div style=\"position: absolute; top: -10000px; width: 0px; height: 0px;\"><div><iframe name=\"fb_xdm_frame_https\" id=\"fb_xdm_frame_https\" aria-hidden=\"true\" title=\"Facebook Cross Domain Communication Frame\" tabindex=\"-1\" frameborder=\"0\" allowtransparency=\"true\" allowfullscreen=\"true\" scrolling=\"no\" allow=\"encrypted-media\" src=\"https://staticxx.facebook.com/connect/xd_arbiter.php?version=45#channel=f32b86a249e5138&amp;origin=https%3A%2F%2Fhobbyful.co.kr\" style=\"border: none;\"></iframe></div><div></div></div></div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("HF.DATA.params = {};\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/page/magazine.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/static/js/module/HF._init.js?bid=bHasJk4dKL\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
